### ISSUE TITLE
MFT.py: broken format string

### ISSUE THREAD

**Issue by PoorBillionaire** [williballenthin/INDXParse#24]
Greetings--

Line 1324 in MFT.py handles the instances in which a file provided by the User is not found by the parser. The code for this is below along with its output, which throws a TypeError as the result of a broken format string:
```
raise KeyError("Path not found: " % path)
```
```
dev@computer:~/INDXParse$ python get_file_info.py ~/MFT "doesnotexist"
Traceback (most recent call last):
File "get_file_info.py", line 416, in
main()
File "get_file_info.py", line 412, in main
record = enum.get_record_by_path(path)
File "/home/dev/INDXParse/MFT.py", line 1324, in get_record_by_path
raise KeyError("Path not found: " % path)
TypeError: not all arguments converted during string formatting
```

The proposed change at line 1324 in MFT.py:

```
raise KeyError("Path not found: %s" % path)
```

Results:
```
dev@computer:~/INDXParse$ python get_file_info.py ~/MFT "doesnotexist"
Traceback (most recent call last):
File "get_file_info.py", line 416, in
main()
File "get_file_info.py", line 412, in main
record = enum.get_record_by_path(path)
File "/home/dev/INDXParse/MFT.py", line 1324, in get_record_by_path
raise KeyError("Path not found: %s" % path)
KeyError: 'Path not found: doesnotexist'
```

**Comment by williballenthin** [comment]
great catch! thanks for reporting the issue. if you re-open #23 i'd be happy to merge it.

**Comment by williballenthin** [comment]
sidenote: if you'd like to automate MFT parsing, there's more recent code available in `python-ntfs` here: https://github.com/williballenthin/python-ntfs
