### ISSUE TITLE
Invalid INDX ID

### ISSUE THREAD

**Issue by yani1shu** [williballenthin/INDXParse#26]
I'm trying to parse a $I30 file and get the following error:

C:\Users\User\Desktop\INDXParse-master>INDXParse.py -d -v $I30
FILENAME,       PHYSICAL SIZE,  LOGICAL SIZE,   MODIFIED TIME,  ACCESSED TIME,  CHANGED TIME,   CREATED TIME
DEBUG:INDXParse:HEADER @ 0x0.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\INDXParse-master\INDXParse.py", line 918, in <module>
    h = NTATTR_STANDARD_INDEX_HEADER(b, off, False)
  File "C:\Users\yschiff\Desktop\INDXParse-master\INDXParse.py", line 291, in __init__
    raise ParseException("Invalid INDX ID at beginning of block at %r bytes of stream, and non-null data encountered %r bytes into the block." % (offset, off))
__main__.ParseException: Invalid INDX ID at beginning of block at 0 bytes of stream, and non-null data encountered 0 bytes into the block.

I've confirmed that the first four bytes of $I30 file are INDX.

**Comment by williballenthin** [comment]
any chance you can share the index data?

**Comment by yani1shu** [comment]
yeah, i tried it on a non-client file and am getting the same error.
[$I30.zip](https://github.com/williballenthin/INDXParse/files/285257/I30.zip)

**Comment by williballenthin** [comment]
Excellent, thanks. I'll take a look and reproduce the issue.

**Comment by williballenthin** [comment]
hm, I'm not able to reproduce this issue on my system. Would you confirm which python version you are running. Are you using Python 2.x or Python 3.x?

**Comment by jimwillingham** [comment]
Got the same problem here on a carved INDX file -- any resolution by chance?

**Comment by williballenthin** [comment]
@jimwillingham can you share the source data so I can reproduce the issue? In the past, I was not able to verify the issue, which made triaging it difficult. You can email me the file directly if you would like the data to remain private.

**Comment by IndustrialOne** [comment]
I have the same problem and I sent you an e-mail with the INDX data. Did you look at it? Thanks.

**Comment by williballenthin** [comment]
file received and issue reproduced. triaging now.

**Comment by williballenthin** [comment]
found the cause: running under python3.

INDXParse was written back in the python2.7 days, and as such, assumes bytes and strings are the same thing. they're not, and this is emphasized in python3+. specifically, when INDXParse tests for the magic header "INDX" it looks for the string, when it should be testing bytes (see [here](https://github.com/williballenthin/INDXParse/blob/1b32736cf9f15d916f7c026346be068fdbe86cf2/INDXParse.py#L287)).

an immediate fix is to ensure you are using python2, eg:

    λ ~/env2/Scripts/python --version
    Python 2.7.15

the long term fix would be to update INDXParse to run on both py2 and py3.

**Comment by williballenthin** [comment]
i'll add a check to INDXParse so that it will bail with a meaningful message if running under py3

**Comment by IndustrialOne** [comment]
Thanks, running in Python 2.7 fixed it, but you should recommend Python 2.7 specifically because it didn't work under Python 2.5 either.
