### ISSUE TITLE
I have a question about your tool T.T from south korea....

### ISSUE THREAD

**Issue by SonSeungHo** [williballenthin/INDXParse#27]
```
DEBUG:INDXParse:HEADER @ 0x0.
Traceback (most recent call last):
  File "INDXParse.py", line 918, in <module>
    h = NTATTR_STANDARD_INDEX_HEADER(b, off, False)
  File "INDXParse.py", line 291, in __init__
    raise ParseException("Invalid INDX ID at beginning of block at %r bytes of stream, and non-null data encountered %r bytes into the block." % (offset, off))
__main__.ParseException: Invalid INDX ID at beginning of block at 0 bytes of stream, and non-null data encountered 0 bytes into the block.
```
I can't understand this error...
what python version do you recommended....

**Comment by thinrope** [comment]
python-2.7, see https://github.com/williballenthin/INDXParse/commit/ca08236b0f70798cb6f89785820c9b82ee0c66ff
