### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mike-bailey** [williballenthin/INDXParse#28]
Had to redact some details but got this error in list_mft when running against an MFT. Happy to try to provide details as needed but may or may not be able to provide them.
```
python tools/INDXParse/list_mft.py --json redacted/mft/\$MFT > redacted/mft/list_mft.json

Traceback (most recent call last):
  File "tools/INDXParse/list_mft.py", line 326, in <module>
    main()
  File "tools/INDXParse/list_mft.py", line 313, in main
    m = make_model(record, record_path)
  File "/redacted/tools/INDXParse/get_file_info.py", line 249, in make_model
    m = make_filename_information_model(e.filename_information())
  File "/redacted/tools/INDXParse/get_file_info.py", line 123, in make_filename_information_model
    "type": ["POSIX", "WIN32", "DOS 8.3", "WIN32 + DOS 8.3"][attr.filename_type()],
IndexError: list index out of range
```

**Comment by williballenthin** [comment]
hey @mike-bailey 

good catch. i wonder if this is due to some corrupted data, or if there is an unexpected filename type. would you attempt to figure out what value its getting from `attr.filename_type()`? if you're not comfortable editing the scripts, i'm also happy to do it, but there'll be a few roundtrips of code exchange.

1. figure out which mft record is causing the error. add a `try`/`except` around like 123 and have it print the current record number before doing a `sys.exit()`.
2. update `get-file-info.py` to print the raw `attr.filename_type()` instead of the array index value.

if the mft record that breaks this script is not sensitive, it might help me understand the data that causes this issue. if it is sensitive, i totally understand if you can't share it.

**Comment by mike-bailey** [comment]
I'll look into it, thank you.

**Comment by mike-bailey** [comment]
I'm awaiting permission to release the details of my findings (am a lowly intern) but I have decent reason to believe it's just corrupted.

**Comment by mike-bailey** [comment]
attr.filename_type returns `240` on exception catch. 
The MFT file itself is definitely unsharable. On trying to get the attr properties, I actually also hit `UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)`. 
In order of:
```attr.filename()
get_flags(attr.flags())
attr.logical_size()
attr.physical_size()
create_safe_datetime(attr.modified_time)
create_safe_datetime(attr.accessed_time)
create_safe_datetime(attr.changed_time)
create_safe_datetime(attr.created_time)
MREF(attr.mft_parent_reference()),
MSEQNO(attr.mft_parent_reference())
```

It's returned:

```
绞Ϭ璀8
['offline', 'system', 'not-indexed', 'has-view-index', 'encrypted', 'directory-dos', 'has-indx']
4295491640
1310744
1601-01-01 00:00:00.111568
1601-01-01 00:00:00.000002
1666-02-11 09:24:43.249075
1601-01-13 09:05:45.372982
10695453729818 0
```

So I guess it is corrupted

**Comment by mike-bailey** [comment]
This occurred again for what it's worth. While it's safe to say it's probably a corrupt MFT, it'd be nice to get a second opinion. Thank you.
