### ISSUE TITLE
TypeError: can't compare datetime.datetime to NoneType

### ISSUE THREAD

**Issue by yampelo** [williballenthin/INDXParse#29]
Is it possible to add default date when the datetime is none? I can't export to JSON because of this sorted line:
```
python list_mft.py $MFT_ --json > test.txt
Traceback (most recent call last):
  File "list_mft.py", line 326, in <module>
    main()
  File "list_mft.py", line 313, in main
    m = make_model(record, record_path)
  File "/private/tmp/INDXParse/get_file_info.py", line 220, in make_model
    "timeline": get_timeline_entries(record),
  File "/private/tmp/INDXParse/get_file_info.py", line 115, in get_timeline_entries
    return sorted(entries, key=lambda x: x["timestamp"])
TypeError: can't compare datetime.datetime to NoneType
```

https://github.com/williballenthin/INDXParse/blob/868ae168b73fd8d44016c8ee54c2a50bf9501d95/get_file_info.py#L115

Something like

```python
mindate = datetime.date(datetime.MINYEAR, 1, 1)

return sorted(entries, key=lambda x: x["timestamp"] or mindate)
```

**Comment by williballenthin** [comment]
this is a good idea! would you be willing to submit a PR with the proposed changes?

**Comment by yampelo** [comment]
Sure!, let me find my fork and ill make the PR request.
