### ISSUE TITLE
Errors upon installation

### ISSUE THREAD

**Issue by nov3mb3r** [williballenthin/INDXParse#32]
Upon running : INDXParse.py -c '$MFT' 
i get the following errors
```
usr/local/bin/INDXParse.py:` line 27: __version__: command not found
import: not authorized `sys' @ error/constitute.c/WriteImage/1028.
import: not authorized `time' @ error/constitute.c/WriteImage/1028.
import: not authorized `array' @ error/constitute.c/WriteImage/1028.
import: not authorized `struct' @ error/constitute.c/WriteImage/1028.
import: not authorized `logging' @ error/constitute.c/WriteImage/1028.
from: can't read /var/mail/datetime
import: not authorized `argparse' @ error/constitute.c/WriteImage/1028.
/usr/local/bin/INDXParse.py: line 39: syntax error near unexpected token `('
/usr/local/bin/INDXParse.py: line 39: `g_logger = logging.getLogger("INDXParse")'

```

**Comment by williballenthin** [comment]
Would you please try re-running the program using the python interpreter explicitly? That is, something like:

```
python2 /usr/local/bin/INDXParse.py ...
```

**Comment by nov3mb3r** [comment]
```
$ python2 /usr/local/bin/INDXParse.py -c '$MFT'
FILENAME,	PHYSICAL SIZE,	LOGICAL SIZE,	MODIFIED TIME,	ACCESSED TIME,	CHANGED TIME,	CREATED TIME
Traceback (most recent call last):
  File "/usr/local/bin/INDXParse.py", line 922, in <module>
    h = NTATTR_STANDARD_INDEX_HEADER(b, off, False)
  File "/usr/local/bin/INDXParse.py", line 295, in __init__
    raise ParseException("Invalid INDX ID at beginning of block at %r bytes of stream, and non-null data encountered %r bytes into the block." % (offset, off))
__main__.ParseException: Invalid INDX ID at beginning of block at 0 bytes of stream, and non-null data encountered 0 bytes into the block.

```
Could it be a problem from my side ? But I have successfully parsed MFT with another program....

**Comment by williballenthin** [comment]
this error looks a lot better. in the first example, your system was choosing the wrong interpreter, so things were getting confused. 

in the second example, the script is running under python - that's good! it's failing because the expected magic value `INDX` is not found at offset 0x0. I presume this is because you are trying to pass an MFT file to the program. this script is meant to be used against INDX buffers extracted via another program, such as by carving. it won't work against an MFT.
