### ISSUE TITLE
Invalid INDX ID at beginning of block at %r bytes of stream, and non-null data encountered %r bytes into the block." % (offset, off))

### ISSUE THREAD

**Issue by josemilagre** [williballenthin/INDXParse#35]
```
$ python INDXParse.py -c -d '$I30' 

FILENAME,	PHYSICAL SIZE,	LOGICAL SIZE,	MODIFIED TIME,	ACCESSED TIME,	CHANGED TIME,	CREATED TIME
Traceback (most recent call last):
  File "INDXParse.py", line 918, in <module>
    h = NTATTR_STANDARD_INDEX_HEADER(b, off, False)
  File "INDXParse.py", line 291, in __init__
    raise ParseException("Invalid INDX ID at beginning of block at %r bytes of stream, and non-null data encountered %r bytes into the block." % (offset, off))
__main__.ParseException: Invalid INDX ID at beginning of block at 0 bytes of stream, and non-null data encountered 0 bytes into the block.
```

**Comment by tobraha** [comment]
Hey @josemilagre - I just ran into this as well. Looks like there are still a few minor adjustments needed to work with Python 3.

I was able to get INDXParse.py working with this quick 'n dirty patch:

```diff
diff --git a/INDXParse.py b/INDXParse.py
index c6852dc..dd29899 100644
--- a/INDXParse.py
+++ b/INDXParse.py
@@ -208,7 +208,7 @@ class Block(object):
         """
         start = self._offset + offset
         end = start + 2 * length
-        return self._buf[start:end].tostring().decode("utf16")
+        return self._buf[start:end].tobytes().decode("utf16")

     def unpack_binary(self, offset, length):
         """
@@ -284,7 +284,7 @@ class NTATTR_STANDARD_INDEX_HEADER(Block):
         self._is_null_block = False

         _magic = self.unpack_string(0, 4)
-        if _magic != "INDX":
+        if _magic != b'INDX':
             off = 0x0
             while off < min(len(buf) - offset, INDEX_NODE_BLOCK_SIZE):
                 if self.unpack_byte(off) != 0:
@@ -935,7 +935,7 @@ if __name__ == '__main__':
         if results.deleted:
             for e in h.deleted_entries():
                 fn = e.filename() + " (slack at %s)" % (hex(e.offset()))
-                bad_fn = e.filename().encode("ascii", "replace") + " (slack at %s)(error decoding filename)" % (hex(e.offset()))
+                bad_fn = (e.filename().encode("ascii", "replace")).decode('utf-8') + " (slack at %s)(error decoding filename)" % (hex(e.offset()))
                 if do_csv:
                     try:
                         print((entry_dir_csv(e, fn)))
```

P.S. I promise to submit a PR once I get around to cleaning this up 😞

**Comment by williballenthin** [comment]
thanks @tobraha ! happy to merge a PR when you're able to create one :-)
